version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data:
